apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher-test
  labels:
    app: log-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-watcher
  template:
    metadata:
      labels:
        app: log-watcher
    spec:
      containers:
      - name: log-watcher
        image: traxiny/log-watcher:testv3.2
        command: ["./log-watcher"] #for testing
        #args: ["-c","sleep 2h"]
        imagePullPolicy: Always
        resources:
          requests:
            memory: 100Mi
            cpu: 1000m
          limits:
            memory: 500Mi
            cpu: 2000m
        securityContext:
          runAsUser: 1000
        env:
        - name: FILTER
          value: "hello-*"
      restartPolicy: Always
        