apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher-test
  labels:
    app: log-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-watcher
  template:
    metadata:
      labels:
        app: log-watcher
    spec:
      containers:
      - name: log-watcher
        image: traxiny/log-watcher:testv2.5
        command: ["./log-watcher"] #for testing
        #args: ["-c","sleep 2h"]
        imagePullPolicy: Always
        resources:
          requests:
            memory: 100Mi
            cpu: 1000m
          limits:
            memory: 500Mi
            cpu: 2000m
        securityContext:
          runAsUser: 1000
#        env:
#        - name: POD_NAMESPACE
#          valueFrom:
#            fieldRef:
#            fieldPath: metadata.namespace
      restartPolicy: Always
        