apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-watcher
  labels:
    app: log-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-watcher
  template:
    metadata:
      labels:
        app: log-watcher
    spec:
      volumes:
      - name: shared-logs
        emptyDir: {}
      containers:
      - name: log-watcher
        image: traxiny/log-watcher:V1
        imagePullPolicy: Always
        command: ["./log-watcher-starter"] 
        volumeMounts:
        - name: shared-logs
          mountPath: /tmp
        resources:
          requests:
            memory: 100Mi
            cpu: 1000m
          limits:
            memory: 500Mi
            cpu: 2000m
        securityContext:
          runAsUser: 1000
        env:
        - name: NAME_FILTER
          value: "hello-*"
      - name: file-beat
        image: docker.elastic.co/beats/filebeat:8.2.2
        imagePullPolicy: IfNotPresent
        command: [] #filebeat setup command
        volumeMounts:
        - name: shared-logs
          mountPath: /tmp #where the files will be
        resources:
          requests:
            memory: 100Mi
            cpu: 1000m
          limits:
            memory: 500Mi
            cpu: 2000m
        securityContext:
          runAsUser: 1000
        env:
        #the config file
